// Code generated by sqlc. DO NOT EDIT.
// source: cve_enrichment.sql

package sql

import (
	"context"
)

const bulkClearFixVersions = `-- name: BulkClearFixVersions :execrows
UPDATE
    vulnerabilities
SET
    fix_version = NULL,
    updated_at = NOW()
FROM (
    SELECT
        unnest($1::TEXT[]) AS cve_id,
        unnest($2::TEXT[]) AS package) AS data
WHERE
    vulnerabilities.cve_id = data.cve_id
    AND vulnerabilities.package = data.package
    AND vulnerabilities.fix_version IS NOT NULL
`

type BulkClearFixVersionsParams struct {
	CveIds   []string
	Packages []string
}

func (q *Queries) BulkClearFixVersions(ctx context.Context, arg BulkClearFixVersionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkClearFixVersions, arg.CveIds, arg.Packages)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkUpdateFixVersions = `-- name: BulkUpdateFixVersions :execrows
UPDATE
    vulnerabilities
SET
    fix_version = data.fix_version,
    updated_at = NOW()
FROM (
    SELECT
        unnest($1::TEXT[]) AS cve_id,
        unnest($2::TEXT[]) AS package,
        unnest($3::TEXT[]) AS fix_version) AS data
WHERE
    vulnerabilities.cve_id = data.cve_id
    AND vulnerabilities.package = data.package
    AND vulnerabilities.fix_version IS DISTINCT FROM data.fix_version
`

type BulkUpdateFixVersionsParams struct {
	CveIds      []string
	Packages    []string
	FixVersions []string
}

func (q *Queries) BulkUpdateFixVersions(ctx context.Context, arg BulkUpdateFixVersionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpdateFixVersions, arg.CveIds, arg.Packages, arg.FixVersions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVulnerabilitiesForOsvEnrichment = `-- name: GetVulnerabilitiesForOsvEnrichment :many
SELECT DISTINCT
    cve_id,
    package
FROM
    vulnerabilities
WHERE
    cve_id != ''
    AND package != ''
    AND package NOT LIKE 'pkg:apk/%'
    AND package NOT LIKE 'pkg:deb/%'
ORDER BY
    cve_id, package
`

type GetVulnerabilitiesForOsvEnrichmentRow struct {
	CveID   string
	Package string
}

// apk/deb excluded: OSV has no purl-tagged fix data for OS-distro packages.
func (q *Queries) GetVulnerabilitiesForOsvEnrichment(ctx context.Context) ([]*GetVulnerabilitiesForOsvEnrichmentRow, error) {
	rows, err := q.db.Query(ctx, getVulnerabilitiesForOsvEnrichment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetVulnerabilitiesForOsvEnrichmentRow{}
	for rows.Next() {
		var i GetVulnerabilitiesForOsvEnrichmentRow
		if err := rows.Scan(&i.CveID, &i.Package); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshCveKevFlags = `-- name: RefreshCveKevFlags :execrows
UPDATE
    cve
SET
    has_kev_entry = k.has_kev_entry,
    known_ransomware_use = k.known_ransomware_use,
    updated_at = NOW()
FROM (
    SELECT
        c.cve_id,
        COUNT(s.source) > 0 AS has_kev_entry,
        COALESCE(bool_or(s.known_ransomware_use), FALSE) AS known_ransomware_use
    FROM
        cve c
        LEFT JOIN cve_kev_source s ON s.cve_id = c.cve_id
    GROUP BY
        c.cve_id) AS k
WHERE
    cve.cve_id = k.cve_id
    AND (cve.has_kev_entry != k.has_kev_entry
        OR cve.known_ransomware_use != k.known_ransomware_use)
`

func (q *Queries) RefreshCveKevFlags(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, refreshCveKevFlags)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertKevSourceEntries = `-- name: UpsertKevSourceEntries :execrows
INSERT INTO cve_kev_source (cve_id, source, known_ransomware_use)
SELECT
    d.cve_id,
    d.source,
    d.known_ransomware_use
FROM (
    SELECT
        unnest($1::TEXT[]) AS cve_id,
        unnest($2::TEXT[]) AS source,
        unnest($3::BOOLEAN[]) AS known_ransomware_use) AS d
    JOIN cve c ON c.cve_id = d.cve_id
ON CONFLICT (cve_id, source)
    DO UPDATE SET
        known_ransomware_use = EXCLUDED.known_ransomware_use,
        last_seen_at = NOW()
`

type UpsertKevSourceEntriesParams struct {
	CveIds             []string
	Sources            []string
	KnownRansomwareUse []bool
}

// Rows are never deleted (see CONTEXT.md).
func (q *Queries) UpsertKevSourceEntries(ctx context.Context, arg UpsertKevSourceEntriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertKevSourceEntries, arg.CveIds, arg.Sources, arg.KnownRansomwareUse)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
