// Code generated by sqlc. DO NOT EDIT.
// source: cve_enrichment.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkClearFixVersions = `-- name: BulkClearFixVersions :execrows
UPDATE
    vulnerabilities
SET
    fix_version = NULL,
    updated_at = NOW()
WHERE
    id = ANY ($1::UUID[])
    AND fix_version IS NOT NULL
`

func (q *Queries) BulkClearFixVersions(ctx context.Context, vulnerabilityIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, bulkClearFixVersions, vulnerabilityIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkUpdateFixVersions = `-- name: BulkUpdateFixVersions :execrows
UPDATE
    vulnerabilities
SET
    fix_version = data.fix_version,
    updated_at = NOW()
FROM (
    SELECT
        unnest($1::UUID[]) AS id,
        unnest($2::TEXT[]) AS fix_version) AS data
WHERE
    vulnerabilities.id = data.id
    AND vulnerabilities.fix_version IS DISTINCT FROM data.fix_version
`

type BulkUpdateFixVersionsParams struct {
	VulnerabilityIds []pgtype.UUID
	FixVersions      []string
}

func (q *Queries) BulkUpdateFixVersions(ctx context.Context, arg BulkUpdateFixVersionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpdateFixVersions, arg.VulnerabilityIds, arg.FixVersions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkUpdateKevData = `-- name: BulkUpdateKevData :execrows
UPDATE
    cve
SET
    has_kev_entry = TRUE,
    known_ransomware_use = data.known_ransomware_use,
    updated_at = NOW()
FROM (
    SELECT
        unnest($1::TEXT[]) AS cve_id,
        unnest($2::BOOLEAN[]) AS known_ransomware_use) AS data
WHERE
    cve.cve_id = data.cve_id
    AND (cve.has_kev_entry = FALSE
        OR cve.known_ransomware_use != data.known_ransomware_use)
`

type BulkUpdateKevDataParams struct {
	CveIds             []string
	KnownRansomwareUse []bool
}

func (q *Queries) BulkUpdateKevData(ctx context.Context, arg BulkUpdateKevDataParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpdateKevData, arg.CveIds, arg.KnownRansomwareUse)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVulnerabilitiesForOsvEnrichment = `-- name: GetVulnerabilitiesForOsvEnrichment :many
SELECT
    id,
    cve_id,
    package
FROM
    vulnerabilities
WHERE
    package != ''
    AND (cve_id LIKE 'CVE-%'
        OR cve_id LIKE 'GHSA-%')
ORDER BY
    id
`

type GetVulnerabilitiesForOsvEnrichmentRow struct {
	ID      pgtype.UUID
	CveID   string
	Package string
}

func (q *Queries) GetVulnerabilitiesForOsvEnrichment(ctx context.Context) ([]*GetVulnerabilitiesForOsvEnrichmentRow, error) {
	rows, err := q.db.Query(ctx, getVulnerabilitiesForOsvEnrichment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetVulnerabilitiesForOsvEnrichmentRow{}
	for rows.Next() {
		var i GetVulnerabilitiesForOsvEnrichmentRow
		if err := rows.Scan(&i.ID, &i.CveID, &i.Package); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
