// Code generated by sqlc. DO NOT EDIT.
// source: package_registry_hash.sql

package sql

import (
	"context"
)

const bulkUpsertPackageRegistryHashes = `-- name: BulkUpsertPackageRegistryHashes :execrows
INSERT INTO package_registry_hashes(
    package,
    registry_hash,
    hash_algorithm,
    resolver,
    resolved_at)
SELECT
    unnest($1::TEXT[]),
    unnest($2::TEXT[]),
    unnest($3::TEXT[]),
    unnest($4::TEXT[]),
    NOW()
ON CONFLICT (package)
    DO UPDATE SET
        registry_hash = excluded.registry_hash,
        hash_algorithm = excluded.hash_algorithm,
        resolver = excluded.resolver,
        resolved_at = excluded.resolved_at
`

type BulkUpsertPackageRegistryHashesParams struct {
	Packages       []string
	RegistryHashes []string
	HashAlgorithms []string
	Resolvers      []string
}

func (q *Queries) BulkUpsertPackageRegistryHashes(ctx context.Context, arg BulkUpsertPackageRegistryHashesParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpsertPackageRegistryHashes,
		arg.Packages,
		arg.RegistryHashes,
		arg.HashAlgorithms,
		arg.Resolvers,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPackageRegistryHashes = `-- name: GetPackageRegistryHashes :many
SELECT
    package,
    registry_hash,
    hash_algorithm,
    resolver,
    resolved_at
FROM
    package_registry_hashes
WHERE
    package = ANY ($1::TEXT[])
ORDER BY
    package
`

func (q *Queries) GetPackageRegistryHashes(ctx context.Context, packages []string) ([]*PackageRegistryHash, error) {
	rows, err := q.db.Query(ctx, getPackageRegistryHashes, packages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PackageRegistryHash{}
	for rows.Next() {
		var i PackageRegistryHash
		if err := rows.Scan(
			&i.Package,
			&i.RegistryHash,
			&i.HashAlgorithm,
			&i.Resolver,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackagesNeedingRegistryHashResolution = `-- name: GetPackagesNeedingRegistryHashResolution :many
SELECT DISTINCT
    v.package
FROM
    vulnerabilities v
    LEFT JOIN package_registry_hashes h ON h.package = v.package
WHERE
    v.package != ''
    AND h.package IS NULL
ORDER BY
    v.package
`

func (q *Queries) GetPackagesNeedingRegistryHashResolution(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getPackagesNeedingRegistryHashResolution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var package_ string
		if err := rows.Scan(&package_); err != nil {
			return nil, err
		}
		items = append(items, package_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
