// Code generated by sqlc. DO NOT EDIT.
// source: sources.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSourceRef = `-- name: CreateSourceRef :exec
INSERT INTO source_refs(
    image_name,
    image_tag,
    source_id,
    source_type
)
VALUES (
        $1,
        $2,
        $3,
           $4
       ) ON CONFLICT
    DO NOTHING
`

type CreateSourceRefParams struct {
	ImageName  string
	ImageTag   string
	SourceID   pgtype.UUID
	SourceType string
}

func (q *Queries) CreateSourceRef(ctx context.Context, arg CreateSourceRefParams) error {
	_, err := q.db.Exec(ctx, createSourceRef,
		arg.ImageName,
		arg.ImageTag,
		arg.SourceID,
		arg.SourceType,
	)
	return err
}

const deleteSourceRef = `-- name: DeleteSourceRef :exec
DELETE
FROM source_refs
WHERE image_name = $1
  AND image_tag = $2
  AND source_type = $3
`

type DeleteSourceRefParams struct {
	ImageName  string
	ImageTag   string
	SourceType string
}

func (q *Queries) DeleteSourceRef(ctx context.Context, arg DeleteSourceRefParams) error {
	_, err := q.db.Exec(ctx, deleteSourceRef, arg.ImageName, arg.ImageTag, arg.SourceType)
	return err
}

const getSourceRef = `-- name: GetSourceRef :one
SELECT id, source_id, source_type, created_at, updated_at, image_name, image_tag
FROM source_refs
WHERE image_name = $1
  AND image_tag = $2
  AND source_type = $3
ORDER BY
    (source_id, source_type) DESC
`

type GetSourceRefParams struct {
	ImageName  string
	ImageTag   string
	SourceType string
}

func (q *Queries) GetSourceRef(ctx context.Context, arg GetSourceRefParams) (*SourceRef, error) {
	row := q.db.QueryRow(ctx, getSourceRef, arg.ImageName, arg.ImageTag, arg.SourceType)
	var i SourceRef
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageName,
		&i.ImageTag,
	)
	return &i, err
}
