apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: v13s-docker-credentials
  labels:
    {{- include "v13s.labels" . | nindent 4 }}
stringData:
  ".dockerconfigjson": {{ .Values.dockerconfigjson | quote }}
