apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "v13s.fullname" . }}
  labels:
    {{- include "v13s.labels" . | nindent 4 }}
stringData:
  ".dockerconfigjson": {{ .Values.dockerconfigjson | quote }}
