apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: "{{ .Release.Name }}-fqdn"
  labels:
    {{ include "v13s.labels" . | nindent 4 }}
spec:
  egress:
  - ports:
    - port: 80
      protocol: TCP
    to:
    - fqdns:
      - metadata.google.internal
  - ports:
    - port: 443
      protocol: TCP
    to:
    - fqdns:
      - private.googleapis.com
  podSelector:
    matchLabels:
      {{ include "v13s.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
