apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "v13s.name" . }}-grpc
  labels:
    {{- include "v13s.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      grpc_read_timeout 86400s;
      grpc_send_timeout 86400s;
      client_body_timeout 86400s;
      grpc_next_upstream_tries 2;
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "v13s.fullname" . }}
                port:
                  name: grpc
                  number: 3001