apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-lease"
  labels:
    {{- include "v13s.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Release.Name }}-lease"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: "{{ .Release.Namespace }}"
