apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "v13s.fullname" . }}
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - to:
        - namespaceSelector: { }
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - to:
        - podSelector:
            matchLabels:
              {{- include "dependencytrack.selectorLabels" . | nindent 14 }}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
---