apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "v13s.fullname" . }}
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
        - port: 80
          protocol: TCP
    - to:
        - namespaceSelector: { }
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - to:
        - podSelector:
            matchLabels:
              {{- include "dependencytrack.selectorLabels" . | nindent 14 }}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
---