apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-workload-vulnerability-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  groups:
    - name: workload-vulnerability-alerts
      rules:
        - alert: "workload critical vulnerabilities"
          expr: v13s_workload_vulnerabilities{severity="CRITICAL", workload_namespace="{{ .Release.Namespace }}"} > 0
          for: 10m
          labels:
            namespace: nais-system
            severity: warning
            channel: nais-alerts-info
            alert_type: custom
          annotations:
            summary: |
              {{ ":rotating_light: CRITICAL vulnerabilities in workload `{{ $labels.workload_name }}`" }}
            description: |
              {{ "Workload `{{ $labels.workload_name }}` in namespace `{{ $labels.workload_namespace }}` has {{ $value | printf \"%.0f\" }} critical vulnerabilities. Please investigate immediately." }}
            consequence: Potential security risk; workload may be exploitable
            action: |
              Check vulnerabilities in Salsa. Consider patching or redeploying the affected workload.
              {{ "https://salsa.{{ .Values.fasit.tenant.name }}.cloud.nais.io/projects?searchText={{ $labels.workload_name }}" }}

        - alert: "workload high riskScore"
          expr: v13s_workload_risk_score{workload_namespace="{{ .Release.Namespace }}"} > 100
          for: 10m
          labels:
            namespace: nais-system
            severity: warning
            channel: nais-alerts-info
            alert_type: custom
          annotations:
            summary: |
              {{ ":warning: High risk score for workload `{{ $labels.workload_name }}`" }}
            description: |
              {{ "Workload `{{ $labels.workload_name }}` in namespace `{{ $labels.workload_namespace }}` has a risk score of {{ $value | printf \"%.0f\" }}. Please review and mitigate potential security or operational issues." }}
            consequence: Potential security or operational risk
            action: |
              Investigate the workload and consider patching, redeploying, or other mitigations as needed
              https://salsa.{{ .Values.fasit.tenant.name }}.cloud.nais.io/projects?searchText=%2Fnais%2F
