{{- if contains "nav" .Values.fasit.tenant.name }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-namespace-vulnerability-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  groups:
    - name: namespace-vulnerability-alerts
      rules:
        - alert: "namespace critical vulnerabilities"
          expr: max by (workload_namespace) (
            v13s_workload_vulnerabilities{
            severity="CRITICAL",
            workload_namespace=~"nais-system|nais"
            }
            ) > 0
          for: 30m
          labels:
            namespace: nais-system
            severity: warning
            channel: nais-alerts-info
            alert_type: custom
            repeat_interval: 1d
          annotations:
            summary: |
              {{ ":rotating_light: CRITICAL vulnerabilities in namespace `{{ $labels.workload_namespace }}`" }}
            description: |
              {{ "Namespace `{{ $labels.workload_namespace }}` has workloads with critical vulnerabilities in one or more clusters." }}
              https://salsa.{{ .Values.fasit.tenant.name }}.cloud.nais.io/projects?searchText=nais-io
            consequence: Potential security risk; workload may be exploitable
            action: |
              Check vulnerabilities in Salsa. Consider patching or redeploying the affected workload.

        - alert: "namespace high risk-score"
          expr: max by (workload_namespace) (
            v13s_workload_risk_score{
            workload_namespace=~"nais-system|nais"
            }
            ) > 250
          for: 30m
          labels:
            namespace: nais-system
            severity: warning
            channel: nais-alerts-info
            alert_type: custom
            repeat_interval: 1d
          annotations:
            summary: |
              {{ ":warning: High risk score in namespace `{{ $labels.workload_namespace }}`" }}
            description: |
              {{ "Namespace `{{ $labels.workload_namespace }}` has workloads with risk scores above threshold in one or more clusters" }}

              Check details in Salsa:
              https://salsa.{{ .Values.fasit.tenant.name }}.cloud.nais.io/projects?searchText=nais-io
            consequence: Potential security or operational risk
            action: |
              Investigate the workloads in Salsa. Consider patching, redeploying, or other mitigations as needed.
{{- end }}

