apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "v13s.fullname" . }}
  labels:
    {{- include "v13s.labels" . | nindent 4 }}
stringData:
  V13S_INTERNAL_LISTEN_ADDR: ":8000"
  V13S_UPDATE_INTERVAL: "{{ .Values.updateInterval }}"
  V13S_DEPENDENCYTRACK_URL: "{{ .Values.dependencytrack.url }}"
  V13S_DEPENDENCYTRACK_USERNAME: "{{ .Values.dependencytrack.username }}"
  V13S_DEPENDENCYTRACK_PASSWORD: "{{ .Values.dependencytrack.password }}"
  V13S_DEPENDENCYTRACK_TEAM: "{{ .Values.dependencytrack.team }}"
  V13S_DATABASE_URL: "postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@127.0.0.1:5432/{{ .Values.database.name }}?sslmode=disable"
  V13S_AUTHORIZED_SERVICE_ACCOUNTS: "{{ .Values.auth.serviceAccounts | join "," }}"
  V13S_REQUIRED_AUDIENCE: "{{ .Values.auth.audience }}"
  V13S_LOG_LEVEL: "{{ .Values.logLevel }}"
  V13S_LOG_FORMAT: "{{ .Values.logFormat }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-collector:4317"
