// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: management.proto

package management

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Workload      string                 `protobuf:"bytes,3,opt,name=workload,proto3" json:"workload,omitempty"`
	WorkloadType  string                 `protobuf:"bytes,4,opt,name=workload_type,json=workloadType,proto3" json:"workload_type,omitempty"`
	ImageName     string                 `protobuf:"bytes,5,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageTag      string                 `protobuf:"bytes,6,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkloadRequest) Reset() {
	*x = RegisterWorkloadRequest{}
	mi := &file_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkloadRequest) ProtoMessage() {}

func (x *RegisterWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkloadRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkloadRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *RegisterWorkloadRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterWorkloadRequest) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *RegisterWorkloadRequest) GetWorkloadType() string {
	if x != nil {
		return x.WorkloadType
	}
	return ""
}

func (x *RegisterWorkloadRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *RegisterWorkloadRequest) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *RegisterWorkloadRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkloadResponse) Reset() {
	*x = RegisterWorkloadResponse{}
	mi := &file_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkloadResponse) ProtoMessage() {}

func (x *RegisterWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkloadResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{2}
}

type GetWorkloadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *string                `protobuf:"bytes,1,opt,name=cluster,proto3,oneof" json:"cluster,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Workload      *string                `protobuf:"bytes,3,opt,name=workload,proto3,oneof" json:"workload,omitempty"`
	WorkloadType  *string                `protobuf:"bytes,4,opt,name=workload_type,json=workloadType,proto3,oneof" json:"workload_type,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadStatusRequest) Reset() {
	*x = GetWorkloadStatusRequest{}
	mi := &file_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadStatusRequest) ProtoMessage() {}

func (x *GetWorkloadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadStatusRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkloadStatusRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *GetWorkloadStatusRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *GetWorkloadStatusRequest) GetWorkload() string {
	if x != nil && x.Workload != nil {
		return *x.Workload
	}
	return ""
}

func (x *GetWorkloadStatusRequest) GetWorkloadType() string {
	if x != nil && x.WorkloadType != nil {
		return *x.WorkloadType
	}
	return ""
}

func (x *GetWorkloadStatusRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWorkloadStatusRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type WorkloadStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Cluster           string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespace         string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Workload          string                 `protobuf:"bytes,3,opt,name=workload,proto3" json:"workload,omitempty"`
	WorkloadType      string                 `protobuf:"bytes,4,opt,name=workload_type,json=workloadType,proto3" json:"workload_type,omitempty"`
	WorkloadState     string                 `protobuf:"bytes,5,opt,name=workload_state,json=workloadState,proto3" json:"workload_state,omitempty"`
	ImageState        string                 `protobuf:"bytes,6,opt,name=image_state,json=imageState,proto3" json:"image_state,omitempty"`
	ImageName         string                 `protobuf:"bytes,7,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageTag          string                 `protobuf:"bytes,8,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	Jobs              []*Job                 `protobuf:"bytes,9,rep,name=jobs,proto3" json:"jobs,omitempty"`
	WorkloadUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=workload_updated_at,json=workloadUpdatedAt,proto3" json:"workload_updated_at,omitempty"`
	ImageUpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=image_updated_at,json=imageUpdatedAt,proto3" json:"image_updated_at,omitempty"`
	WorkloadId        string                 `protobuf:"bytes,12,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{4}
}

func (x *WorkloadStatus) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *WorkloadStatus) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadStatus) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *WorkloadStatus) GetWorkloadType() string {
	if x != nil {
		return x.WorkloadType
	}
	return ""
}

func (x *WorkloadStatus) GetWorkloadState() string {
	if x != nil {
		return x.WorkloadState
	}
	return ""
}

func (x *WorkloadStatus) GetImageState() string {
	if x != nil {
		return x.ImageState
	}
	return ""
}

func (x *WorkloadStatus) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *WorkloadStatus) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *WorkloadStatus) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *WorkloadStatus) GetWorkloadUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WorkloadUpdatedAt
	}
	return nil
}

func (x *WorkloadStatus) GetImageUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ImageUpdatedAt
	}
	return nil
}

func (x *WorkloadStatus) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

type GetWorkloadStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkloadStatus  []*WorkloadStatus      `protobuf:"bytes,1,rep,name=workload_status,json=workloadStatus,proto3" json:"workload_status,omitempty"`
	TotalCount      int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasNextPage     bool                   `protobuf:"varint,3,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPreviousPage bool                   `protobuf:"varint,4,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetWorkloadStatusResponse) Reset() {
	*x = GetWorkloadStatusResponse{}
	mi := &file_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadStatusResponse) ProtoMessage() {}

func (x *GetWorkloadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadStatusResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkloadStatusResponse) GetWorkloadStatus() []*WorkloadStatus {
	if x != nil {
		return x.WorkloadStatus
	}
	return nil
}

func (x *GetWorkloadStatusResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetWorkloadStatusResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *GetWorkloadStatusResponse) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Attempts      int32                  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Errors        string                 `protobuf:"bytes,6,opt,name=errors,proto3" json:"errors,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{6}
}

func (x *Job) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Job) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Job) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Job) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Job) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Job) GetErrors() string {
	if x != nil {
		return x.Errors
	}
	return ""
}

func (x *Job) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type GetWorkloadJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *string                `protobuf:"bytes,1,opt,name=cluster,proto3,oneof" json:"cluster,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Workload      *string                `protobuf:"bytes,3,opt,name=workload,proto3,oneof" json:"workload,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadJobsRequest) Reset() {
	*x = GetWorkloadJobsRequest{}
	mi := &file_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadJobsRequest) ProtoMessage() {}

func (x *GetWorkloadJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadJobsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadJobsRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{7}
}

func (x *GetWorkloadJobsRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *GetWorkloadJobsRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *GetWorkloadJobsRequest) GetWorkload() string {
	if x != nil && x.Workload != nil {
		return *x.Workload
	}
	return ""
}

func (x *GetWorkloadJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWorkloadJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetWorkloadJobsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Jobs            []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	TotalCount      int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasNextPage     bool                   `protobuf:"varint,3,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPreviousPage bool                   `protobuf:"varint,4,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetWorkloadJobsResponse) Reset() {
	*x = GetWorkloadJobsResponse{}
	mi := &file_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadJobsResponse) ProtoMessage() {}

func (x *GetWorkloadJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadJobsResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadJobsResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkloadJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *GetWorkloadJobsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetWorkloadJobsResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *GetWorkloadJobsResponse) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

type ResyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *string                `protobuf:"bytes,1,opt,name=cluster,proto3,oneof" json:"cluster,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Workload      *string                `protobuf:"bytes,3,opt,name=workload,proto3,oneof" json:"workload,omitempty"`
	WorkloadType  *string                `protobuf:"bytes,4,opt,name=workload_type,json=workloadType,proto3,oneof" json:"workload_type,omitempty"`
	WorkloadState *string                `protobuf:"bytes,5,opt,name=workload_state,json=workloadState,proto3,oneof" json:"workload_state,omitempty"`
	ImageState    *string                `protobuf:"bytes,6,opt,name=image_state,json=imageState,proto3,oneof" json:"image_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResyncRequest) Reset() {
	*x = ResyncRequest{}
	mi := &file_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResyncRequest) ProtoMessage() {}

func (x *ResyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResyncRequest.ProtoReflect.Descriptor instead.
func (*ResyncRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{9}
}

func (x *ResyncRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *ResyncRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ResyncRequest) GetWorkload() string {
	if x != nil && x.Workload != nil {
		return *x.Workload
	}
	return ""
}

func (x *ResyncRequest) GetWorkloadType() string {
	if x != nil && x.WorkloadType != nil {
		return *x.WorkloadType
	}
	return ""
}

func (x *ResyncRequest) GetWorkloadState() string {
	if x != nil && x.WorkloadState != nil {
		return *x.WorkloadState
	}
	return ""
}

func (x *ResyncRequest) GetImageState() string {
	if x != nil && x.ImageState != nil {
		return *x.ImageState
	}
	return ""
}

type ResyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumWorkloads  int32                  `protobuf:"varint,1,opt,name=num_workloads,json=numWorkloads,proto3" json:"num_workloads,omitempty"`
	Workloads     []string               `protobuf:"bytes,2,rep,name=workloads,proto3" json:"workloads,omitempty"` // List of workload identifiers that were resynced
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResyncResponse) Reset() {
	*x = ResyncResponse{}
	mi := &file_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResyncResponse) ProtoMessage() {}

func (x *ResyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResyncResponse.ProtoReflect.Descriptor instead.
func (*ResyncResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{10}
}

func (x *ResyncResponse) GetNumWorkloads() int32 {
	if x != nil {
		return x.NumWorkloads
	}
	return 0
}

func (x *ResyncResponse) GetWorkloads() []string {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type DeleteWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Workload      string                 `protobuf:"bytes,3,opt,name=workload,proto3" json:"workload,omitempty"`
	WorkloadType  *string                `protobuf:"bytes,4,opt,name=workload_type,json=workloadType,proto3,oneof" json:"workload_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkloadRequest) Reset() {
	*x = DeleteWorkloadRequest{}
	mi := &file_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkloadRequest) ProtoMessage() {}

func (x *DeleteWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkloadRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteWorkloadRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *DeleteWorkloadRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteWorkloadRequest) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *DeleteWorkloadRequest) GetWorkloadType() string {
	if x != nil && x.WorkloadType != nil {
		return *x.WorkloadType
	}
	return ""
}

type DeleteWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkloadResponse) Reset() {
	*x = DeleteWorkloadResponse{}
	mi := &file_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkloadResponse) ProtoMessage() {}

func (x *DeleteWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkloadResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{12}
}

var File_management_proto protoreflect.FileDescriptor

const file_management_proto_rawDesc = "" +
	"\n" +
	"\x10management.proto\x12\x11v13s.api.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x02\n" +
	"\x17RegisterWorkloadRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bworkload\x18\x03 \x01(\tR\bworkload\x12#\n" +
	"\rworkload_type\x18\x04 \x01(\tR\fworkloadType\x12\x1d\n" +
	"\n" +
	"image_name\x18\x05 \x01(\tR\timageName\x12\x1b\n" +
	"\timage_tag\x18\x06 \x01(\tR\bimageTag\x12<\n" +
	"\bmetadata\x18\a \x01(\v2\x1b.v13s.api.protobuf.MetadataH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\x86\x01\n" +
	"\bMetadata\x12?\n" +
	"\x06labels\x18\x01 \x03(\v2'.v13s.api.protobuf.Metadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1a\n" +
	"\x18RegisterWorkloadResponse\"\x8e\x02\n" +
	"\x18GetWorkloadStatusRequest\x12\x1d\n" +
	"\acluster\x18\x01 \x01(\tH\x00R\acluster\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x01R\tnamespace\x88\x01\x01\x12\x1f\n" +
	"\bworkload\x18\x03 \x01(\tH\x02R\bworkload\x88\x01\x01\x12(\n" +
	"\rworkload_type\x18\x04 \x01(\tH\x03R\fworkloadType\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offsetB\n" +
	"\n" +
	"\b_clusterB\f\n" +
	"\n" +
	"_namespaceB\v\n" +
	"\t_workloadB\x10\n" +
	"\x0e_workload_type\"\xec\x03\n" +
	"\x0eWorkloadStatus\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bworkload\x18\x03 \x01(\tR\bworkload\x12#\n" +
	"\rworkload_type\x18\x04 \x01(\tR\fworkloadType\x12%\n" +
	"\x0eworkload_state\x18\x05 \x01(\tR\rworkloadState\x12\x1f\n" +
	"\vimage_state\x18\x06 \x01(\tR\n" +
	"imageState\x12\x1d\n" +
	"\n" +
	"image_name\x18\a \x01(\tR\timageName\x12\x1b\n" +
	"\timage_tag\x18\b \x01(\tR\bimageTag\x12*\n" +
	"\x04jobs\x18\t \x03(\v2\x16.v13s.api.protobuf.JobR\x04jobs\x12J\n" +
	"\x13workload_updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x11workloadUpdatedAt\x12D\n" +
	"\x10image_updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0eimageUpdatedAt\x12\x1f\n" +
	"\vworkload_id\x18\f \x01(\tR\n" +
	"workloadId\"\xd8\x01\n" +
	"\x19GetWorkloadStatusResponse\x12J\n" +
	"\x0fworkload_status\x18\x01 \x03(\v2!.v13s.api.protobuf.WorkloadStatusR\x0eworkloadStatus\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\"\n" +
	"\rhas_next_page\x18\x03 \x01(\bR\vhasNextPage\x12*\n" +
	"\x11has_previous_page\x18\x04 \x01(\bR\x0fhasPreviousPage\"\xcc\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\x12\x16\n" +
	"\x06errors\x18\x06 \x01(\tR\x06errors\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xd0\x01\n" +
	"\x16GetWorkloadJobsRequest\x12\x1d\n" +
	"\acluster\x18\x01 \x01(\tH\x00R\acluster\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x01R\tnamespace\x88\x01\x01\x12\x1f\n" +
	"\bworkload\x18\x03 \x01(\tH\x02R\bworkload\x88\x01\x01\x12\x14\n" +
	"\x05Limit\x18\x04 \x01(\x05R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x05 \x01(\x05R\x06OffsetB\n" +
	"\n" +
	"\b_clusterB\f\n" +
	"\n" +
	"_namespaceB\v\n" +
	"\t_workload\"\xb6\x01\n" +
	"\x17GetWorkloadJobsResponse\x12*\n" +
	"\x04jobs\x18\x01 \x03(\v2\x16.v13s.api.protobuf.JobR\x04jobs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\"\n" +
	"\rhas_next_page\x18\x03 \x01(\bR\vhasNextPage\x12*\n" +
	"\x11has_previous_page\x18\x04 \x01(\bR\x0fhasPreviousPage\"\xca\x02\n" +
	"\rResyncRequest\x12\x1d\n" +
	"\acluster\x18\x01 \x01(\tH\x00R\acluster\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x01R\tnamespace\x88\x01\x01\x12\x1f\n" +
	"\bworkload\x18\x03 \x01(\tH\x02R\bworkload\x88\x01\x01\x12(\n" +
	"\rworkload_type\x18\x04 \x01(\tH\x03R\fworkloadType\x88\x01\x01\x12*\n" +
	"\x0eworkload_state\x18\x05 \x01(\tH\x04R\rworkloadState\x88\x01\x01\x12$\n" +
	"\vimage_state\x18\x06 \x01(\tH\x05R\n" +
	"imageState\x88\x01\x01B\n" +
	"\n" +
	"\b_clusterB\f\n" +
	"\n" +
	"_namespaceB\v\n" +
	"\t_workloadB\x10\n" +
	"\x0e_workload_typeB\x11\n" +
	"\x0f_workload_stateB\x0e\n" +
	"\f_image_state\"S\n" +
	"\x0eResyncResponse\x12#\n" +
	"\rnum_workloads\x18\x01 \x01(\x05R\fnumWorkloads\x12\x1c\n" +
	"\tworkloads\x18\x02 \x03(\tR\tworkloads\"\xa7\x01\n" +
	"\x15DeleteWorkloadRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bworkload\x18\x03 \x01(\tR\bworkload\x12(\n" +
	"\rworkload_type\x18\x04 \x01(\tH\x00R\fworkloadType\x88\x01\x01B\x10\n" +
	"\x0e_workload_type\"\x18\n" +
	"\x16DeleteWorkloadResponse2\x89\x04\n" +
	"\n" +
	"Management\x12k\n" +
	"\x10RegisterWorkload\x12*.v13s.api.protobuf.RegisterWorkloadRequest\x1a+.v13s.api.protobuf.RegisterWorkloadResponse\x12n\n" +
	"\x11GetWorkloadStatus\x12+.v13s.api.protobuf.GetWorkloadStatusRequest\x1a,.v13s.api.protobuf.GetWorkloadStatusResponse\x12h\n" +
	"\x0fGetWorkloadJobs\x12).v13s.api.protobuf.GetWorkloadJobsRequest\x1a*.v13s.api.protobuf.GetWorkloadJobsResponse\x12M\n" +
	"\x06Resync\x12 .v13s.api.protobuf.ResyncRequest\x1a!.v13s.api.protobuf.ResyncResponse\x12e\n" +
	"\x0eDeleteWorkload\x12(.v13s.api.protobuf.DeleteWorkloadRequest\x1a).v13s.api.protobuf.DeleteWorkloadResponseB&Z$./pkg/api/vulnerabilities/managementb\x06proto3"

var (
	file_management_proto_rawDescOnce sync.Once
	file_management_proto_rawDescData []byte
)

func file_management_proto_rawDescGZIP() []byte {
	file_management_proto_rawDescOnce.Do(func() {
		file_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)))
	})
	return file_management_proto_rawDescData
}

var file_management_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_management_proto_goTypes = []any{
	(*RegisterWorkloadRequest)(nil),   // 0: v13s.api.protobuf.RegisterWorkloadRequest
	(*Metadata)(nil),                  // 1: v13s.api.protobuf.Metadata
	(*RegisterWorkloadResponse)(nil),  // 2: v13s.api.protobuf.RegisterWorkloadResponse
	(*GetWorkloadStatusRequest)(nil),  // 3: v13s.api.protobuf.GetWorkloadStatusRequest
	(*WorkloadStatus)(nil),            // 4: v13s.api.protobuf.WorkloadStatus
	(*GetWorkloadStatusResponse)(nil), // 5: v13s.api.protobuf.GetWorkloadStatusResponse
	(*Job)(nil),                       // 6: v13s.api.protobuf.Job
	(*GetWorkloadJobsRequest)(nil),    // 7: v13s.api.protobuf.GetWorkloadJobsRequest
	(*GetWorkloadJobsResponse)(nil),   // 8: v13s.api.protobuf.GetWorkloadJobsResponse
	(*ResyncRequest)(nil),             // 9: v13s.api.protobuf.ResyncRequest
	(*ResyncResponse)(nil),            // 10: v13s.api.protobuf.ResyncResponse
	(*DeleteWorkloadRequest)(nil),     // 11: v13s.api.protobuf.DeleteWorkloadRequest
	(*DeleteWorkloadResponse)(nil),    // 12: v13s.api.protobuf.DeleteWorkloadResponse
	nil,                               // 13: v13s.api.protobuf.Metadata.LabelsEntry
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_management_proto_depIdxs = []int32{
	1,  // 0: v13s.api.protobuf.RegisterWorkloadRequest.metadata:type_name -> v13s.api.protobuf.Metadata
	13, // 1: v13s.api.protobuf.Metadata.labels:type_name -> v13s.api.protobuf.Metadata.LabelsEntry
	6,  // 2: v13s.api.protobuf.WorkloadStatus.jobs:type_name -> v13s.api.protobuf.Job
	14, // 3: v13s.api.protobuf.WorkloadStatus.workload_updated_at:type_name -> google.protobuf.Timestamp
	14, // 4: v13s.api.protobuf.WorkloadStatus.image_updated_at:type_name -> google.protobuf.Timestamp
	4,  // 5: v13s.api.protobuf.GetWorkloadStatusResponse.workload_status:type_name -> v13s.api.protobuf.WorkloadStatus
	14, // 6: v13s.api.protobuf.Job.finished_at:type_name -> google.protobuf.Timestamp
	6,  // 7: v13s.api.protobuf.GetWorkloadJobsResponse.jobs:type_name -> v13s.api.protobuf.Job
	0,  // 8: v13s.api.protobuf.Management.RegisterWorkload:input_type -> v13s.api.protobuf.RegisterWorkloadRequest
	3,  // 9: v13s.api.protobuf.Management.GetWorkloadStatus:input_type -> v13s.api.protobuf.GetWorkloadStatusRequest
	7,  // 10: v13s.api.protobuf.Management.GetWorkloadJobs:input_type -> v13s.api.protobuf.GetWorkloadJobsRequest
	9,  // 11: v13s.api.protobuf.Management.Resync:input_type -> v13s.api.protobuf.ResyncRequest
	11, // 12: v13s.api.protobuf.Management.DeleteWorkload:input_type -> v13s.api.protobuf.DeleteWorkloadRequest
	2,  // 13: v13s.api.protobuf.Management.RegisterWorkload:output_type -> v13s.api.protobuf.RegisterWorkloadResponse
	5,  // 14: v13s.api.protobuf.Management.GetWorkloadStatus:output_type -> v13s.api.protobuf.GetWorkloadStatusResponse
	8,  // 15: v13s.api.protobuf.Management.GetWorkloadJobs:output_type -> v13s.api.protobuf.GetWorkloadJobsResponse
	10, // 16: v13s.api.protobuf.Management.Resync:output_type -> v13s.api.protobuf.ResyncResponse
	12, // 17: v13s.api.protobuf.Management.DeleteWorkload:output_type -> v13s.api.protobuf.DeleteWorkloadResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_management_proto_init() }
func file_management_proto_init() {
	if File_management_proto != nil {
		return
	}
	file_management_proto_msgTypes[0].OneofWrappers = []any{}
	file_management_proto_msgTypes[3].OneofWrappers = []any{}
	file_management_proto_msgTypes[7].OneofWrappers = []any{}
	file_management_proto_msgTypes[9].OneofWrappers = []any{}
	file_management_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_proto_goTypes,
		DependencyIndexes: file_management_proto_depIdxs,
		MessageInfos:      file_management_proto_msgTypes,
	}.Build()
	File_management_proto = out.File
	file_management_proto_goTypes = nil
	file_management_proto_depIdxs = nil
}
